spring:
  application:
    name: trend-trading-backtest-service
  sleuth:
    sampler:
      probability: 1.0
      rate: 1000
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      addresses: 127.0.0.1:5672
      queue: zipkin
      username: admin
      password: pass.123
  rabbitmq:
    host: localhost
    username: admin
    password: pass.123
    port: 5672

server:
  port: 8071



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


feign:
  client:
    config:
      default:
        readTimeout: 1000
  circuitbreaker:
    enabled: true