spring:
  application:
    name: trend-trading-backtest-service


server:
  port: 8071



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


feign:
  client:
    config:
      default:
        readTimeout: 1000
        connectTimeout:
  circuitbreaker:
    enabled: true