spring:
  application:
    name: index-data-service
  redis:
    port: 6379
    database: 0
    host: localhost
  sleuth:
    sampler:
      probability: 1.0
      rate: 1000
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      addresses: 127.0.0.1:5672
      queue: zipkin
      username: admin
      password: pass.123
  rabbitmq:
    host: localhost
    username: admin
    password: pass.123
    port: 5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
