spring:
  application:
    name: index-config-service
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zhufan12/trendInvestingConfig.git
          searchPaths: /
          force-pull: true
          default-label: master


server:
  port: 8041


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: index-config-service